## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: 220.0
accel_x_max: 255.0
accel_y_min: -60.0
accel_y_max: 60.0
accel_z_min: 203.0
accel_z_max: 238.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-1184.40, 383.531, -2082.66]
magn_ellipsoid_transform: [[0.854617, 0.0711872, -0.265014], [0.0711872, 0.836050, 0.0334617], [-0.265014, 0.0334617, 0.445070]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -53.35
gyro_average_offset_y: -4.3
gyro_average_offset_z: -3.32
